import { useCallback, useEffect, useState } from "react";
import { authApi, identityApi, type AuthStatus, type IdentityUser, type MembershipRecord, type OrganizationRecord } from "../../api";

export function OrganizationCenter() {
  const [session, setSession] = useState<AuthStatus | null>(null); const [organizations, setOrganizations] = useState<OrganizationRecord[]>([]); const [users, setUsers] = useState<IdentityUser[]>([]); const [memberships, setMemberships] = useState<MembershipRecord[]>([]);
  const [selected, setSelected] = useState(""); const [orgId, setOrgId] = useState(""); const [orgName, setOrgName] = useState("");
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [role, setRole] = useState("viewer"); const [workspaceIds, setWorkspaceIds] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => {
    const status = await authApi.status(); setSession(status);
    if (!status.identity_enabled) return;
    const [orgData, userData] = await Promise.all([identityApi.organizations(), identityApi.users()]); setOrganizations(orgData.organizations || []); setUsers(userData.users || []);
    const current = selected || status.organization_id || orgData.organizations?.[0]?.organization_id || ""; setSelected(current);
    if (current) setMemberships((await identityApi.memberships(current)).memberships || []);
  }, [selected]);
  useEffect(() => { load().catch(() => setError("组织信息读取失败")); }, [load]);
  async function createOrg() { setBusy(true); setError(""); try { await identityApi.createOrganization(orgId.trim(), orgName.trim()); setOrgId(""); setOrgName(""); await load(); } catch (err) { setError(String((err as { message?: string })?.message || "组织创建失败")); } finally { setBusy(false); } }
  async function saveUser() { setBusy(true); setError(""); try { await identityApi.saveUser({ username: username.trim(), password, role, organization_id: selected, workspace_ids: workspaceIds.split(",").map((item) => item.trim()).filter(Boolean) }); setUsername(""); setPassword(""); await load(); } catch (err) { setError(String((err as { message?: string })?.message || "成员保存失败")); } finally { setBusy(false); } }
  return <div className="page organization-center"><header className="page-header ui-page-header"><div><h1>组织与成员 <span>Organizations</span></h1><p className="subtitle">按组织隔离工作区，统一管理成员角色和可访问范围。</p></div></header><div className="page-body">{error ? <div className="extension-center-error" role="alert">{error}</div> : null}{session && !session.identity_enabled ? <section className="organization-disabled"><h2>尚未启用组织身份模式</h2><p>当前仍使用单账户登录。设置 AGENT_PLATFORM_IDENTITY_ENABLED=true 后，可创建组织、成员和工作区权限。</p></section> : <div className="organization-layout"><aside className="organization-list"><div className="workflow-panel-title"><h2>组织</h2><span>{organizations.length}</span></div>{organizations.map((item) => <button key={item.organization_id} className={selected === item.organization_id ? "selected" : ""} onClick={() => setSelected(item.organization_id)}><b>{item.name}</b><small>{item.organization_id} · {item.workspace_ids.length} 个工作区</small></button>)}{session?.platform_admin ? <div className="organization-create"><input className="input" value={orgName} onChange={(event) => setOrgName(event.target.value)} placeholder="新组织名称" /><input className="input" value={orgId} onChange={(event) => setOrgId(event.target.value)} placeholder="组织标识，如 team_a" /><button className="btn secondary" disabled={busy || !orgId || !orgName} onClick={() => void createOrg()}>创建组织</button></div> : null}</aside><main className="organization-main"><section className="organization-current"><div><h2>{organizations.find((item) => item.organization_id === selected)?.name || selected}</h2><p>当前登录：{session?.username} · {session?.role || "管理员"}</p></div><span>{memberships.length} 名成员</span></section><div className="organization-member-grid">{memberships.map((item) => <article key={item.username}><div><b>{item.username}</b><small>{item.role}</small></div><p>{item.workspace_ids.length ? item.workspace_ids.join("、") : "尚未分配工作区"}</p></article>)}</div><section className="organization-user-form"><h3>添加或更新成员</h3><div><input className="input" value={username} onChange={(event) => setUsername(event.target.value)} placeholder="账户" /><input className="input" type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="临时密码" /><select className="input" value={role} onChange={(event) => setRole(event.target.value)}><option value="viewer">只读成员</option><option value="operator">运行人员</option><option value="developer">流程开发者</option><option value="admin">组织管理员</option></select><input className="input" value={workspaceIds} onChange={(event) => setWorkspaceIds(event.target.value)} placeholder="工作区标识，多个用逗号分隔" /><button className="btn primary" disabled={busy || !selected || !username || !password} onClick={() => void saveUser()}>保存成员</button></div></section><section className="organization-users"><h3>可管理账户</h3><p>{users.map((item) => `${item.username}（${item.role}）`).join(" · ") || "暂无账户"}</p></section></main></div>}</div></div>;
}
